#!/usr/bin/env python3
"""Merges some XML files generated by various scripts.
"""
import sys
import os
import os.path
import xml.etree.ElementTree as ET

basePath = os.path.dirname(os.path.realpath(__file__))
objs1 = ET.parse(os.path.join(basePath, '../dump/objects.xml')).getroot()
objs2 = ET.parse(os.path.join(basePath, '../dump/objects2.xml')).getroot()

for objId in range(0x5C5):
    obj1 = objs1.findall("./object[@id='0x%04X']" % objId)[0]
    obj2 = objs2.findall("./object[@id='0x%04X']" % objId)[0]

    for map in obj1.findall("./map"):
        mid = map.get('id')
        map2 = obj2.findall("./map[@id='%s']" % mid)[0]
        map.set('count', map2.get('count'))
        map.text = None
print(ET.tostring(objs1, encoding='unicode'))
